# Generated by Django 3.1.3 on 2021-01-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0002_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
    ]
